import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Play, Eye, Calendar, MapPin, Hash, Share2, Download, Heart, MessageCircle } from 'lucide-react';
import { useAuth, api } from '../contexts/AuthContext';
import toast from 'react-hot-toast';
import RoleConfirmationModal from '../components/RoleConfirmationModal';
import NameCaptureModal from '../components/NameCaptureModal';
import LaunchConfirmationModal from '../components/LaunchConfirmationModal'; // ADD THIS IMPORT

interface Content {
  createdAt: string | number | Date;
  _id: string;
  title: string;
  description: string;
  mediaType: 'teaser' | 'trailer' | 'poster' | 'video' | 'image';
  mediaUrl: string;
  thumbnailUrl?: string;
  hashtags: string[];
  location?: string;
  isViewed: boolean;
  viewCount: number;
  isLaunched: boolean;
  socialPlatforms: {
    youtube?: { published: boolean; publishedAt?: string };
    instagram?: { published: boolean; publishedAt?: string };
    twitter?: { published: boolean; publishedAt?: string };
  };
  user: {
    username: string;
    fullName: string;
    avatar?: string;
  };
  analytics: { // Ensure analytics type is consistent with backend
    views: number;
    uniqueViews: number;
    engagementRate: number;
    shares?: number; // Add if available
    likes: number; // Add if available
    comments?: number; // Add if available
  };
  // You might need a 'likedBy' array here if your backend tracks individual likes
  // likedBy?: string[];
}

const getFullMediaUrl = (relativePath: string | undefined): string => {
  if (!relativePath) return '';
  if (relativePath.startsWith('http://') || relativePath.startsWith('https://')) {
    return relativePath;
  }
  return `${import.meta.env.VITE_API_BASE_URL}${relativePath}`;
};

const ViewContent: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user, isAuthenticated, openAuthModal } = useAuth(); // ADDED: user from useAuth
  const [content, setContent] = useState<Content | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [hasViewed, setHasViewed] = useState(false);
  const [showRoleModal, setShowRoleModal] = useState(false);
  const [showNameModal, setShowNameModal] = useState(false);
  const [viewerRole, setViewerRole] = useState<'general' | 'special' | null>(null);
  const [viewerName, setViewerName] = useState<string | null>(null);
  const [showLaunchConfirmation, setShowLaunchConfirmation] = useState(false); // ADDED
  const [isLiked, setIsLiked] = useState(false); // ADDED for Like functionality

  const videoRef = useRef<HTMLVideoElement>(null);

  const fetchContent = useCallback(async () => {
    if (!id) return;
    setIsLoading(true);
    try {
      const response = await api.get(`/v1/content/${id}`);
      setContent(response.data.data);
      if (response.data.data.isViewed) {
        setHasViewed(true);
      }
      // Check initial like status
      if (user && response.data.data.likedBy && response.data.data.likedBy.includes(user.id)) {
        setIsLiked(true);
      }
    } catch (error: any) {
      if (error.response?.status === 404) {
        toast.error('Content not found');
        navigate('/dashboard');
      } else {
        toast.error('Failed to load content');
        console.error("Error fetching content:", error);
      }
    } finally {
      setIsLoading(false);
    }
  }, [id, navigate, user]); // Added user to dependencies for initial like check

  useEffect(() => {
    if (!isAuthenticated) {
      openAuthModal('login');
      setIsLoading(false);
      return;
    }

    const storedRole = localStorage.getItem('viewerRole') as 'general' | 'special' | null;
    const storedName = localStorage.getItem('viewerName');

    if (storedRole && storedName) {
      setViewerRole(storedRole);
      setViewerName(storedName);
      fetchContent();
    } else if (!storedRole) {
      setShowRoleModal(true);
      setIsLoading(false);
    } else {
      setViewerRole(storedRole);
      setShowNameModal(true);
      setIsLoading(false);
    }
  }, [isAuthenticated, openAuthModal, fetchContent]);

  // Debugging logs
  useEffect(() => {
    if (content) {
      console.log('DEBUG: Content object received:', content);
      console.log('DEBUG: content.mediaType:', content.mediaType);
      console.log('DEBUG: content.mediaUrl from API response:', content.mediaUrl);
      const fullMediaUrl = getFullMediaUrl(content.mediaUrl);
      console.log('DEBUG: Full media URL generated by getFullMediaUrl:', fullMediaUrl);
    }
  }, [content]);

  // Refactored markAsViewed to only log the view, launch logic moved to handleLaunchConfirmation
  const markAsViewed = useCallback(async () => {
    if (!content || hasViewed || content.isViewed || !viewerRole || !viewerName) {
      return;
    }

    try {
      await api.put(`/v1/content/${content._id}/view`, { viewerRole, viewerName });
      setHasViewed(true);
      setContent(prev => prev ? { ...prev, isViewed: true, viewCount: prev.viewCount + 1 } : null);
      toast.success("View logged successfully");

    } catch (error) {
      console.error("Error in markAsViewed:", error);
      toast.error("Failed to mark as viewed");
    }
  }, [content, hasViewed, viewerRole, viewerName]);

  // Handler for video ending
  const handleVideoEnded = useCallback(() => {
    if (viewerRole === 'special' && content && !content.isLaunched) {
      setShowLaunchConfirmation(true);
    }
  }, [viewerRole, content]);

  // Handler for custom play overlay click
  const handleOverlayPlay = () => {
    if (videoRef.current) {
      videoRef.current.play();
      setHasViewed(true); // Hide the overlay
    }
  };

  // Handler for Launch Confirmation Modal
  const handleLaunchConfirmation = useCallback(async (proceed: boolean) => {
    setShowLaunchConfirmation(false); // Close the popup

    if (!proceed || !content || !viewerName) {
      toast('Launch cancelled.', { icon: '👋' });
      return;
    }

    try {
      toast.loading('Initiating launch...', { id: 'launchToast' });
      await api.post(`/v1/launch`, {
        contentId: content._id,
        launchedByName: viewerName,
        platforms: { youtube: true, instagram: false } // Assuming only YouTube for now
      });
      toast.success("Content launched successfully!", { id: 'launchToast' });
      setContent(prev => prev ? { ...prev, isLaunched: true } : null);
    } catch (error) {
      console.error("Error launching content:", error);
      toast.error("Failed to launch content. Please try again.", { id: 'launchToast' });
    }
  }, [content, viewerName]);

  const handleShare = async () => {
    if (!content) return;
    if (navigator.share) {
      try {
        await navigator.share({
          title: content.title,
          text: content.description,
          url: window.location.href,
        });
      } catch (error) {
        console.log("Share API error or cancelled:", error);
      }
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast.success('Link copied to clipboard!');
    }
  };

  // --- ADDED: Like functionality ---
  const handleLike = async () => {
    if (!isAuthenticated) {
      openAuthModal('login');
      toast.error('Please log in to like content.');
      return;
    }
    if (!content) return;

    try {
      // API call to like/unlike
      const response = await api.post(`/v1/content/${content._id}/like`);
      setIsLiked(response.data.isLiked); // Update local state based on backend response

      // Optimistically update frontend like count
      setContent(prev => prev ? {
          ...prev,
          analytics: {
              ...prev.analytics,
              likes: response.data.isLiked ? (prev.analytics.likes || 0) + 1 : (prev.analytics.likes || 0) - 1
          }
      } : null);
      toast.success(response.data.message);
    } catch (error) {
      console.error('Error liking content:', error);
      toast.error('Failed to like/unlike content.');
    }
  };
  // --- END ADDED: Like functionality ---

  const handleRoleSelect = (role: "general" | "special") => {
    localStorage.setItem("viewerRole", role);
    setViewerRole(role);
    setShowRoleModal(false);

    const storedName = localStorage.getItem('viewerName');
    if (!storedName) {
      setShowNameModal(true);
    } else {
      setViewerName(storedName);
      fetchContent();
    }
  };

  const handleNameSubmit = (name: string) => {
    localStorage.setItem("viewerName", name);
    setViewerName(name);
    setShowNameModal(false);
    fetchContent();
  };

  if (isLoading) {
    return (
      <div className="container mx-auto px-6 py-8">
        <div className="flex items-center justify-center min-h-[400px] text-white">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
          <p className="ml-4">Loading content...</p>
        </div>
      </div>
    );
  }

  if (showRoleModal) {
    return (
      <RoleConfirmationModal
        open={showRoleModal}
        onClose={() => {
          setShowRoleModal(false);
          navigate('/dashboard');
        }}
        onSelectRole={handleRoleSelect}
      />
    );
  }

  if (showNameModal) {
    return (
      <NameCaptureModal
        open={showNameModal}
        onClose={() => {
          setShowNameModal(false);
          navigate('/dashboard');
        }}
        onNameSubmit={handleNameSubmit}
      />
    );
  }

  if (!content) {
    return (
      <div className="container mx-auto px-6 py-8">
        <div className="text-center py-12">
          <h2 className="text-2xl font-bold text-white mb-4">Content not found or unavailable</h2>
          <button
            onClick={() => navigate('/dashboard')}
            className="px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors"
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  const isVideoContentType = ['teaser', 'trailer', 'video'].includes(content.mediaType);

  return (
    <div className="container mx-auto px-6 py-8">
      <div className="max-w-6xl mx-auto">
        <div className="mb-8">
          <button
            onClick={() => navigate('/dashboard')}
            className="text-gray-300 hover:text-white mb-4 transition-colors"
          >
            ← Back to Dashboard
          </button>
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-3xl font-bold text-white mb-2">{content.title}</h1>
              <div className="flex items-center space-x-4 text-gray-300">
                <span className="flex items-center space-x-1">
                  <Eye className="h-4 w-4" />
                  <span>{content.viewCount} views</span>
                </span>
                <span className="flex items-center space-x-1">
                  <Calendar className="h-4 w-4" />
                  <span>{new Date(content.createdAt).toLocaleDateString()}</span>
                </span>
                {content.location && (
                  <span className="flex items-center space-x-1">
                    <MapPin className="h-4 w-4" />
                    <span>{content.location}</span>
                  </span>
                )}
              </div>
            </div>
            <div className="flex space-x-2">
              <button onClick={handleShare} className="p-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors">
                <Share2 className="h-5 w-5" />
              </button>
              <button className="p-3 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors">
                <Download className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <div className="bg-black rounded-xl overflow-hidden mb-6">
              {isVideoContentType ? (
                <div className="relative">
                  <video
                    ref={videoRef}
                    src={getFullMediaUrl(content.mediaUrl)}
                    poster={getFullMediaUrl(content.thumbnailUrl)}
                    controls
                    className="w-full aspect-video"
                    onPlay={markAsViewed}
                    onEnded={handleVideoEnded}
                    onError={(e) => { console.error('Video error:', e); toast.error('Failed to load video.'); }}
                  />
                  {!hasViewed && !content.isViewed && (
                    <div
                      className="absolute inset-0 bg-black/50 flex items-center justify-center cursor-pointer"
                      onClick={handleOverlayPlay}
                    >
                      <div className="text-center">
                        <Play className="h-16 w-16 text-white mx-auto mb-4" />
                        <p className="text-white text-lg font-medium">
                          Click to watch and log your view
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="relative">
                  <img
                    src={getFullMediaUrl(content.mediaUrl)}
                    alt={content.title}
                    className="w-full aspect-video object-cover"
                    onLoad={markAsViewed}
                    onError={() => toast.error('Failed to load image.')}
                  />
                </div>
              )}
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10 mb-6">
              <h2 className="text-xl font-semibold text-white mb-4">Description</h2>
              <p className="text-gray-300 leading-relaxed">{content.description}</p>
            </div>

            {content.hashtags.length > 0 && (
              <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10">
                <h2 className="text-xl font-semibold text-white mb-4">Hashtags</h2>
                <div className="flex flex-wrap gap-2">
                  {content.hashtags.map((tag, index) => (
                    <span
                      key={index}
                      className="flex items-center space-x-1 px-3 py-1 bg-blue-500/20 text-blue-300 rounded-full text-sm"
                    >
                      <Hash className="h-3 w-3" />
                      <span>{tag}</span>
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="space-y-6">
            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10">
              <h3 className="text-lg font-semibold text-white mb-4">Creator</h3>
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
                  <span className="text-white font-bold">
                    {content.user.fullName.charAt(0).toUpperCase()}
                  </span>
                </div>
                <div>
                  <p className="text-white font-medium">{content.user.fullName}</p>
                  <p className="text-gray-300 text-sm">@{content.user.username}</p>
                </div>
              </div>
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10">
              <h3 className="text-lg font-semibold text-white mb-4">Status</h3>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-gray-300">Type</span>
                  <span className="text-white capitalize">{content.mediaType}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-300">Viewed</span>
                  <span className={`px-2 py-1 rounded-full text-xs ${
                    content.isViewed || hasViewed ? 'bg-green-500/20 text-green-400' : 'bg-gray-500/20 text-gray-400'
                  }`}>
                    {content.isViewed || hasViewed ? 'Yes' : 'No'}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-300">Launched</span>
                  <span className={`px-2 py-1 rounded-full text-xs ${
                    content.isLaunched ? 'bg-purple-500/20 text-purple-400' : 'bg-gray-500/20 text-gray-400'
                  }`}>
                    {content.isLaunched ? 'Yes' : 'No'}
                  </span>
                </div>
              </div>
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10">
              <h3 className="text-lg font-semibold text-white mb-4">Social Media</h3>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-gray-300">YouTube</span>
                  <span className={`px-2 py-1 rounded-full text-xs ${
                    content.socialPlatforms.youtube?.published
                      ? 'bg-red-500/20 text-red-400'
                      : 'bg-gray-500/20 text-gray-400'
                  }`}>
                    {content.socialPlatforms.youtube?.published ? 'Published' : 'Pending'}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-300">Instagram</span>
                  <span className={`px-2 py-1 rounded-full text-xs ${
                    content.socialPlatforms.instagram?.published
                      ? 'bg-pink-500/20 text-pink-400'
                      : 'bg-gray-500/20 text-gray-400'
                  }`}>
                    {content.socialPlatforms.instagram?.published ? 'Published' : 'Pending'}
                  </span>
                </div>
                {content.socialPlatforms.twitter && (
                  <div className="flex items-center justify-between">
                    <span className="text-gray-300">Twitter</span>
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      content.socialPlatforms.twitter?.published
                        ? 'bg-blue-500/20 text-blue-400'
                        : 'bg-gray-500/20 text-gray-400'
                    }`}>
                      {content.socialPlatforms.twitter?.published ? 'Published' : 'Pending'}
                    </span>
                  </div>
                )}
              </div>
            </div>

            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/10">
              <h3 className="text-lg font-semibold text-white mb-4">Actions</h3>
              <div className="space-y-3">
                {/* --- MODIFIED: Like Button --- */}
                <button
                  onClick={handleLike}
                  className={`w-full flex items-center justify-center space-x-2 px-4 py-2 rounded-lg transition-colors ${
                    isLiked ? 'bg-red-600 hover:bg-red-700 text-white' : 'bg-red-500/20 hover:bg-red-500/30 text-red-400'
                  }`}
                >
                  <Heart className="h-4 w-4" />
                  <span>{isLiked ? 'Liked' : 'Like'} ({content.analytics?.likes || 0})</span>
                </button>
                {/* --- END MODIFIED --- */}

                {/* --- MODIFIED: Comment Button (Placeholder) --- */}
                <button className="w-full flex items-center justify-center space-x-2 px-4 py-2 bg-blue-500/20 hover:bg-blue-500/30 text-blue-400 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        disabled // Disabled as comments not implemented yet
                >
                  <MessageCircle className="h-4 w-4" />
                  <span>Comment</span>
                </button>
                {/* --- END MODIFIED --- */}

                <button
                  onClick={handleShare}
                  className="w-full flex items-center justify-center space-x-2 px-4 py-2 bg-green-500/20 hover:bg-green-500/30 text-green-400 rounded-lg transition-colors"
                >
                  <Share2 className="h-4 w-4" />
                  <span>Share</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* --- ADDED: Launch Confirmation Modal --- */}
      {showLaunchConfirmation && content && (
        <LaunchConfirmationModal
          open={showLaunchConfirmation}
          onClose={() => setShowLaunchConfirmation(false)}
          onConfirm={handleLaunchConfirmation}
          title={content.title}
        />
      )}
      {/* --- END ADDED --- */}
    </div>
  );
};

export default ViewContent;